import os

ALPHA_API_KEY = os.getenv("ALPHA_API_KEY")

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

CHECK_INTERVAL = 60

SYMBOL = "XAU"
MARKET = "USD"

EMA_FAST = 20
EMA_SLOW = 50

RSI_PERIOD = 14
